# Generated by Django 4.1 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalancedCultureSortation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalancedCurtureNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50, null=True)),
                ('field', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreLiberalArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreLiberalArtsSortation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialLiberalArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationCiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underGra', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('essentialLiberal', models.IntegerField(null=True)),
                ('choiceLiberal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('distribution', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('prof', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
