# Generated by Django 4.1 on 2022-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationciteria',
            name='deepChoiceMajor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graduationciteria',
            name='deepMajor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graduationciteria',
            name='essMajor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graduationciteria',
            name='manyMajor1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graduationciteria',
            name='subMajor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graduationciteria',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
