# Generated by Django 4.1 on 2022-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_second_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/static/img/person.png', upload_to='image'),
        ),
    ]
