# Generated by Django 4.1 on 2022-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_balancedculture_year_coreliberalarts_year_and_more'),
        ('accounts', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up',
            field=models.ManyToManyField(to='datas.subjects'),
        ),
    ]
