# Generated by Django 4.1 on 2022-08-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedCultureSortation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialLiberalArtsSortation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationCiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underGra', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('essentialLiberal', models.IntegerField(null=True)),
                ('choiceLiberal', models.IntegerField(null=True)),
                ('deepMajor', models.IntegerField(null=True)),
                ('deepChoiceMajor', models.IntegerField(null=True)),
                ('manyMajor1', models.IntegerField(null=True)),
                ('essMajor', models.IntegerField(null=True)),
                ('subMajor', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('distribution', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('prof', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialLiberalArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.essentialliberalartssortation')),
            ],
        ),
        migrations.CreateModel(
            name='BalancedCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.balancedculturesortation')),
            ],
        ),
    ]
