# Generated by Django 4.1 on 2022-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreLiberalArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EssentialLiberalArtsSortation',
            new_name='CoreLiberalArtsSortation',
        ),
        migrations.RemoveField(
            model_name='essentialliberalarts',
            name='sort',
        ),
        migrations.AlterField(
            model_name='balancedculture',
            name='sort',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
