# Generated by Django 4.1 on 2022-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_coreliberalarts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedCurtureNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50, null=True)),
                ('field', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
