# Generated by Django 4.1 on 2022-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_balancedcurturenot'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedculture',
            name='year',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coreliberalarts',
            name='year',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essentialliberalarts',
            name='field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essentialliberalarts',
            name='year',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
