# Generated by Django 4.1 on 2022-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_balancedculture_year_coreliberalarts_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essentialliberalarts',
            old_name='field',
            new_name='sort',
        ),
        migrations.AlterField(
            model_name='balancedculture',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coreliberalarts',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='essentialliberalarts',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
