# Generated by Django 4.1 on 2022-09-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_rename_field_essentialliberalarts_sort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationciteria',
            name='deepChoiceMajor',
        ),
        migrations.RemoveField(
            model_name='graduationciteria',
            name='deepMajor',
        ),
        migrations.RemoveField(
            model_name='graduationciteria',
            name='essMajor',
        ),
        migrations.RemoveField(
            model_name='graduationciteria',
            name='manyMajor1',
        ),
        migrations.RemoveField(
            model_name='graduationciteria',
            name='subMajor',
        ),
        migrations.RemoveField(
            model_name='graduationciteria',
            name='total',
        ),
    ]
